name: strooper
description: Strooper is a game to test the coordination ability between cognitive and visual response of the user.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Bungee
      fonts:
        - asset: fonts/Bungee-Regular.ttf

    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf