name: strooper
description: Strooper is a game to test the coordination ability between cognitive and visual response of the user.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  flutter_circular_text: ^0.3.0

  provider: ^4.3.2+2
  get_it: ^5.0.1

  audioplayers: ^0.16.2

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  # For OS-specific directory paths
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.8.2
  build_runner: ^1.10.4

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Bungee
      fonts:
        - asset: fonts/Bungee-Regular.ttf

    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf